import type { CreateOfferInput } from "@/lib/schemas/offer-schema";
import type { OfferMetadata } from "@/lib/offers/offer-types";

const PRESENCE_METADATA: OfferMetadata = {
  valueBreakdownFr: [
    { label: "4 vidéos", value: "400 000 DA" },
    { label: "5 contenus", value: "75 000 DA" },
    { label: "Landing Page", value: "90 000 DA" },
  ],
  valueBreakdownEn: [
    { label: "4 videos", value: "400,000 DZD" },
    { label: "5 assets", value: "75,000 DZD" },
    { label: "Landing Page", value: "90,000 DZD" },
  ],
  totalValueFr: "565 000 DA",
  totalValueEn: "565,000 DZD",
};

export const V1_OFFER_SEED: CreateOfferInput[] = [
  {
    slug: "presence",
    name: "PRESENCE™",
    nameFr: "PRESENCE™",
    category: "pack",
    description: "Presented clearly and credibly",
    descriptionFr: "Présenté de manière claire et crédible",
    features: [
      "4 strategic videos",
      "5 complementary assets (carousels / posters)",
      "1 shoot day",
      "Landing Page",
    ],
    featuresFr: [
      "4 vidéos stratégiques",
      "5 contenus complémentaires (carrousels / posters)",
      "1 journée de tournage",
      "Landing Page",
    ],
    price: 390_000,
    active: true,
    featured: false,
    studyOnly: false,
    order: 1,
    cta: "Choose Presence",
    ctaFr: "Choisir Presence",
    metadata: PRESENCE_METADATA,
  },
  {
    slug: "authority",
    name: "AUTHORITY™",
    nameFr: "AUTHORITY™",
    category: "pack",
    description: "The safest choice in your market",
    descriptionFr: "Le choix le plus sûr de son marché",
    features: [
      "Everything in Presence",
      "24/7 AI assistant",
      "Pixel Tracking",
      "Automatic qualification",
      "Buyer Intelligence™ collection",
    ],
    featuresFr: [
      "Tout Presence",
      "Assistant IA 24h/24",
      "Pixel Tracking",
      "Qualification automatique",
      "Collecte Buyer Intelligence™",
    ],
    price: 690_000,
    active: true,
    featured: true,
    studyOnly: false,
    order: 2,
    cta: "Choose Authority",
    ctaFr: "Choisir Authority",
    noteEn:
      "The AI assistant automatically responds to prospects, qualifies requests, and guides visitors before contact.",
    noteFr:
      "L'assistant IA répond automatiquement aux prospects, qualifie les demandes et accompagne les visiteurs avant la prise de contact.",
  },
  {
    slug: "growth",
    name: "GROWTH™",
    nameFr: "GROWTH™",
    category: "pack",
    description: "A complete system that turns trust into visits and reservations",
    descriptionFr:
      "Un système complet qui transforme la confiance en visites et en réservations",
    features: [
      "Everything in Authority",
      "Digital infrastructure",
      "Reporting",
      "Buyer Intelligence Engine™",
      "Strategic support",
    ],
    featuresFr: [
      "Tout Authority",
      "Infrastructure digitale",
      "Reporting",
      "Buyer Intelligence Engine™",
      "Accompagnement stratégique",
    ],
    priceLabel: "On request",
    priceLabelFr: "Sur étude",
    active: true,
    featured: false,
    studyOnly: true,
    order: 3,
    cta: "Request a study",
    ctaFr: "Demander une étude",
  },
  {
    slug: "video_strategique",
    name: "Strategic video",
    nameFr: "Vidéo stratégique",
    category: "ala_carte",
    description: "Single strategic video production",
    descriptionFr: "Production d'une vidéo stratégique",
    features: [],
    featuresFr: [],
    price: 100_000,
    active: true,
    featured: false,
    studyOnly: false,
    order: 1,
  },
  {
    slug: "landing_page",
    name: "Landing Page",
    nameFr: "Landing Page",
    category: "ala_carte",
    description: "Conversion-focused landing page",
    descriptionFr: "Landing page orientée conversion",
    features: [],
    featuresFr: [],
    price: 90_000,
    active: true,
    featured: false,
    studyOnly: false,
    order: 2,
  },
  {
    slug: "pixel_tracking",
    name: "Pixel Tracking",
    nameFr: "Pixel Tracking",
    category: "ala_carte",
    description: "Meta / analytics pixel setup",
    descriptionFr: "Configuration pixel Meta / analytics",
    features: [],
    featuresFr: [],
    price: 30_000,
    active: true,
    featured: false,
    studyOnly: false,
    order: 3,
  },
  {
    slug: "carousel_poster",
    name: "Carousel / Poster",
    nameFr: "Carousel / Poster",
    category: "ala_carte",
    description: "Social carousel or poster asset",
    descriptionFr: "Carrousel ou poster pour réseaux sociaux",
    features: [],
    featuresFr: [],
    price: 15_000,
    active: true,
    featured: false,
    studyOnly: false,
    order: 4,
  },
  {
    slug: "assistant_ia",
    name: "AI Assistant™",
    nameFr: "Assistant IA™",
    category: "ala_carte",
    description: "AI assistant for lead qualification",
    descriptionFr: "Assistant IA pour qualification des prospects",
    features: [],
    featuresFr: [],
    priceLabel: "On request",
    priceLabelFr: "Sur étude",
    active: true,
    featured: false,
    studyOnly: true,
    order: 5,
  },
];
