import type { CaseStudy } from "@/lib/types/admin";

export const MOCK_CASE_STUDIES: CaseStudy[] = [
  {
    id: "cs-1",
    title: "Oran Fresh Foods — Viral Reels Campaign",
    clientId: "client-1",
    clientName: "Oran Fresh Foods",
    industry: "Food & Beverage",
    videoUrl: "/vids/scroll-1.mp4",
    thumbnailUrl: "/vids/scroll-1.mp4",
    services: ["Reels Production", "Social Strategy"],
    results: [
      { label: "Follower growth", value: "+340%" },
      { label: "Avg. views per reel", value: "125K" },
      { label: "Leads generated", value: "48" },
    ],
    published: true,
    order: 1,
    createdAt: "2025-12-01T10:00:00.000Z",
  },
  {
    id: "cs-2",
    title: "Maison Cherifi — Brand Identity Launch",
    clientId: "client-2",
    clientName: "Maison Cherifi",
    industry: "Fashion",
    videoUrl: "/vids/scroll-2.mp4",
    services: ["Brand Identity", "Social Content"],
    results: [
      { label: "Brand recognition", value: "+180%" },
      { label: "Website traffic", value: "+95%" },
    ],
    published: true,
    order: 2,
    createdAt: "2026-01-10T14:00:00.000Z",
  },
  {
    id: "cs-3",
    title: "TechOran — Product Launch Video",
    clientId: "client-3",
    clientName: "TechOran Solutions",
    industry: "Technology",
    videoUrl: "/vids/hero.mov",
    services: ["Video Production", "Website"],
    results: [
      { label: "Launch day signups", value: "320" },
      { label: "Video completion rate", value: "78%" },
    ],
    published: true,
    order: 3,
    createdAt: "2026-02-20T09:00:00.000Z",
  },
  {
    id: "cs-4",
    title: "Khelifi Cosmetics — Monthly Content",
    clientId: "client-4",
    clientName: "Khelifi Cosmetics",
    industry: "Beauty",
    videoUrl: "/vids/scroll-3.mp4",
    services: ["Reels Production", "Carousels"],
    results: [
      { label: "Engagement rate", value: "+220%" },
      { label: "Monthly reach", value: "2.1M" },
    ],
    published: false,
    order: 4,
    createdAt: "2026-01-05T08:00:00.000Z",
  },
  {
    id: "cs-5",
    title: "Taleb Restaurant Group — Multi-Location Campaign",
    clientId: "client-7",
    clientName: "Taleb Restaurant Group",
    industry: "Hospitality",
    videoUrl: "/vids/scroll-4.mp4",
    services: ["Reels Production", "Photography", "Automations"],
    results: [
      { label: "Reservations via social", value: "+65%" },
      { label: "Locations covered", value: "4" },
    ],
    published: true,
    order: 5,
    createdAt: "2025-10-15T10:00:00.000Z",
  },
];
