import type { Client } from "@/lib/types/admin";

export const MOCK_CLIENTS: Client[] = [
  {
    id: "client-1",
    name: "Karim Boudiaf",
    company: "Oran Fresh Foods",
    phone: "+213 555 123 456",
    email: "karim@oranfresh.dz",
    industry: "Food & Beverage",
    status: "vip",
    origin: "lead_upgrade",
    originLeadId: "lead-1",
    projectIds: ["proj-1", "proj-2"],
    notes: "Key account — prefers WhatsApp for updates.",
    createdAt: "2025-10-15T10:00:00.000Z",
    lastProjectAt: "2026-02-01T09:00:00.000Z",
    totalRevenue: 850000,
    showOnWebsite: true,
  },
  {
    id: "client-2",
    name: "Nadia Cherifi",
    company: "Maison Cherifi",
    phone: "+213 661 987 654",
    email: "nadia@maisoncherifi.dz",
    industry: "Fashion",
    status: "active",
    origin: "lead_upgrade",
    originLeadId: "lead-5",
    projectIds: ["proj-3"],
    notes: "",
    createdAt: "2025-11-20T14:00:00.000Z",
    lastProjectAt: "2025-12-15T16:00:00.000Z",
    totalRevenue: 320000,
    showOnWebsite: true,
  },
  {
    id: "client-3",
    name: "Youssef Hamidi",
    company: "TechOran Solutions",
    email: "youssef@techoran.dz",
    industry: "Technology",
    status: "active",
    origin: "direct",
    projectIds: ["proj-4"],
    notes: "Startup — budget conscious but high potential.",
    createdAt: "2026-01-08T11:00:00.000Z",
    lastProjectAt: "2026-02-15T11:00:00.000Z",
    totalRevenue: 180000,
    showOnWebsite: false,
  },
  {
    id: "client-4",
    name: "Salima Khelifi",
    company: "Khelifi Cosmetics",
    phone: "+213 770 111 222",
    email: "salima@khelificosmetics.dz",
    industry: "Beauty",
    status: "active",
    origin: "direct",
    projectIds: ["proj-5"],
    notes: "Monthly retainer client.",
    createdAt: "2025-09-01T08:00:00.000Z",
    lastProjectAt: "2026-01-05T08:00:00.000Z",
    totalRevenue: 570000,
    showOnWebsite: true,
  },
  {
    id: "client-5",
    name: "Rachid Meziane",
    company: "Meziane Auto Parts",
    phone: "+213 555 444 333",
    industry: "Automotive",
    status: "inactive",
    origin: "lead_upgrade",
    originLeadId: "lead-8",
    projectIds: ["proj-6"],
    notes: "Project on hold — client paused due to budget.",
    createdAt: "2025-08-10T12:00:00.000Z",
    totalRevenue: 95000,
    showOnWebsite: false,
  },
  {
    id: "client-6",
    name: "Leila Benali",
    company: "Benali Architecture",
    email: "leila@benaliarch.dz",
    industry: "Architecture",
    status: "active",
    origin: "direct",
    projectIds: [],
    notes: "New client — discovery phase.",
    createdAt: "2026-02-20T09:00:00.000Z",
    showOnWebsite: false,
  },
  {
    id: "client-7",
    name: "Omar Taleb",
    company: "Taleb Restaurant Group",
    phone: "+213 661 555 888",
    email: "omar@talebgroupe.dz",
    industry: "Hospitality",
    status: "vip",
    origin: "direct",
    projectIds: [],
    notes: "Multi-location restaurant group — expansion plans.",
    createdAt: "2025-07-01T10:00:00.000Z",
    totalRevenue: 1200000,
    showOnWebsite: true,
  },
  {
    id: "client-8",
    name: "Fatima Zohra",
    company: "FZ Events",
    email: "fz@fzevents.dz",
    industry: "Events",
    status: "active",
    origin: "lead_upgrade",
    originLeadId: "lead-11",
    projectIds: [],
    notes: "",
    createdAt: "2026-01-25T15:00:00.000Z",
    totalRevenue: 75000,
    showOnWebsite: false,
  },
];
