import type { Lead } from "@/lib/types/admin";

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-1",
    name: "Karim Boudiaf",
    company: "Oran Fresh Foods",
    phone: "+213 555 123 456",
    email: "karim@oranfresh.dz",
    source: "instagram",
    utmCampaign: "reels_q4",
    utmMedium: "paid_social",
    pixelEventFired: "Lead",
    interestedIn: ["offer-reels", "offer-brand"],
    stage: "won",
    notes: "Upgraded to client. Interested in ongoing reels.",
    createdAt: "2025-10-01T10:00:00.000Z",
    lastContactedAt: "2025-10-14T16:00:00.000Z",
    assignedTo: "amine",
  },
  {
    id: "lead-2",
    name: "Hocine Belkacem",
    company: "Belkacem Motors",
    phone: "+213 661 222 333",
    email: "hocine@belkacem.dz",
    source: "tiktok",
    utmCampaign: "viral_reels",
    pixelEventFired: "ViewContent",
    interestedIn: ["offer-reels"],
    stage: "new",
    notes: "Saw our TikTok reel about car listings.",
    createdAt: "2026-03-18T09:00:00.000Z",
    assignedTo: "zaki",
  },
  {
    id: "lead-3",
    name: "Meriem Saadi",
    phone: "+213 555 888 999",
    source: "facebook",
    utmMedium: "organic",
    interestedIn: ["offer-photo"],
    stage: "new",
    notes: "DM on Facebook asking about product photos.",
    createdAt: "2026-03-19T14:00:00.000Z",
  },
  {
    id: "lead-4",
    name: "Tarek Amrani",
    company: "Amrani Logistics",
    email: "tarek@amranilog.dz",
    source: "google",
    utmCampaign: "brand_search",
    utmMedium: "cpc",
    pixelEventFired: "Lead",
    interestedIn: ["offer-website"],
    stage: "contacted",
    notes: "Called once — wants a quote for website.",
    createdAt: "2026-03-10T11:00:00.000Z",
    lastContactedAt: "2026-03-12T10:00:00.000Z",
    assignedTo: "anis",
  },
  {
    id: "lead-5",
    name: "Nadia Cherifi",
    company: "Maison Cherifi",
    email: "nadia@maisoncherifi.dz",
    source: "referral",
    interestedIn: ["offer-brand"],
    stage: "won",
    notes: "Referred by Karim Boudiaf.",
    createdAt: "2025-11-10T08:00:00.000Z",
    assignedTo: "amine",
  },
  {
    id: "lead-6",
    name: "Samir Ouahab",
    phone: "+213 770 333 444",
    source: "website",
    pixelEventFired: "Lead",
    interestedIn: ["offer-automation"],
    stage: "qualified",
    notes: "Filled contact form — wants CRM automation.",
    createdAt: "2026-03-05T16:00:00.000Z",
    lastContactedAt: "2026-03-08T09:00:00.000Z",
    assignedTo: "zaki",
  },
  {
    id: "lead-7",
    name: "Amina Bensaïd",
    company: "Bensaïd Pharma",
    email: "amina@bensaiddz.dz",
    source: "cold",
    interestedIn: ["offer-social", "offer-reels"],
    stage: "proposal_sent",
    notes: "Cold outreach — sent proposal for social retainer.",
    createdAt: "2026-02-28T10:00:00.000Z",
    lastContactedAt: "2026-03-15T14:00:00.000Z",
    assignedTo: "amine",
  },
  {
    id: "lead-8",
    name: "Rachid Meziane",
    company: "Meziane Auto Parts",
    phone: "+213 555 444 333",
    source: "instagram",
    interestedIn: ["offer-website"],
    stage: "won",
    notes: "Project paused after upgrade.",
    createdAt: "2025-08-01T12:00:00.000Z",
    assignedTo: "zaki",
  },
  {
    id: "lead-9",
    name: "Djamel Kaci",
    email: "djamel.kaci@gmail.com",
    source: "other",
    interestedIn: ["offer-chatbot"],
    stage: "lost",
    notes: "Went with another agency — price too high.",
    createdAt: "2026-01-15T09:00:00.000Z",
    lastContactedAt: "2026-01-20T11:00:00.000Z",
    assignedTo: "anis",
  },
  {
    id: "lead-10",
    name: "Soraya Hadj",
    company: "Hadj Boutique",
    phone: "+213 661 777 888",
    source: "tiktok",
    utmCampaign: "fashion_reels",
    pixelEventFired: "InitiateCheckout",
    interestedIn: ["offer-reels", "offer-photo"],
    stage: "contacted",
    notes: "Interested in combo package.",
    createdAt: "2026-03-14T13:00:00.000Z",
    lastContactedAt: "2026-03-16T10:00:00.000Z",
    assignedTo: "yacine",
  },
  {
    id: "lead-11",
    name: "Fatima Zohra",
    company: "FZ Events",
    email: "fz@fzevents.dz",
    source: "website",
    pixelEventFired: "Lead",
    interestedIn: ["offer-brand"],
    stage: "won",
    notes: "Booked via website form.",
    createdAt: "2026-01-20T15:00:00.000Z",
    assignedTo: "imen",
  },
  {
    id: "lead-12",
    name: "Bilal Rahmani",
    company: "Rahmani Construction",
    phone: "+213 555 999 000",
    email: "bilal@rahmaniconst.dz",
    source: "google",
    utmCampaign: "construction_ads",
    interestedIn: ["offer-website", "offer-photo"],
    stage: "qualified",
    notes: "Needs website + project portfolio photos.",
    createdAt: "2026-03-01T08:00:00.000Z",
    lastContactedAt: "2026-03-10T16:00:00.000Z",
    assignedTo: "amine",
  },
];
