import type { Offer } from "@/lib/types/admin";

export const MOCK_OFFERS: Offer[] = [
  {
    id: "offer-reels",
    slug: "reels-production",
    name: "Reels Production",
    nameFr: "Production Reels",
    category: "media",
    description: "Short-form video content optimized for Instagram and TikTok virality.",
    descriptionFr: "Contenu vidéo court optimisé pour la viralité Instagram et TikTok.",
    features: [
      "Script + storyboard",
      "Half-day shoot",
      "Editing + captions",
      "3 platform exports",
    ],
    featuresFr: [
      "Script + storyboard",
      "Tournage demi-journée",
      "Montage + sous-titres",
      "3 exports plateformes",
    ],
    priceLabel: "Starting from 80,000 DZD",
    active: true,
    featured: true,
    order: 1,
    cta: "Book a shoot",
  },
  {
    id: "offer-photo",
    slug: "product-photography",
    name: "Product Photography",
    nameFr: "Photographie Produit",
    category: "media",
    description: "Studio and on-location product shots for e-commerce and catalogs.",
    descriptionFr: "Photos produit en studio et sur site pour e-commerce et catalogues.",
    features: ["20 edited photos", "White background option", "48h delivery"],
    price: 45000,
    active: true,
    featured: false,
    order: 2,
  },
  {
    id: "offer-brand",
    slug: "brand-identity",
    name: "Brand Identity Package",
    nameFr: "Identité de Marque",
    category: "brand_content",
    description: "Logo, color palette, typography, and brand guidelines.",
    descriptionFr: "Logo, palette couleurs, typographie et charte graphique.",
    features: ["Logo concepts", "Brand book PDF", "Social templates"],
    priceLabel: "Starting from 120,000 DZD",
    active: true,
    featured: true,
    order: 1,
  },
  {
    id: "offer-social",
    slug: "social-content",
    name: "Monthly Social Content",
    nameFr: "Contenu Social Mensuel",
    category: "brand_content",
    description: "Recurring carousel, poster, and story content for your channels.",
    descriptionFr: "Carrousels, affiches et stories récurrents pour vos canaux.",
    features: ["12 posts/month", "Content calendar", "2 revision rounds"],
    price: 95000,
    active: true,
    featured: false,
    order: 2,
  },
  {
    id: "offer-website",
    slug: "business-website",
    name: "Business Website",
    nameFr: "Site Web Professionnel",
    category: "websites_apps",
    description: "Responsive Next.js website with CMS-ready structure.",
    descriptionFr: "Site Next.js responsive avec structure prête pour CMS.",
    features: ["Up to 8 pages", "Contact forms", "SEO setup", "Mobile-first"],
    priceLabel: "Starting from 200,000 DZD",
    active: true,
    featured: true,
    order: 1,
  },
  {
    id: "offer-app",
    slug: "web-app",
    name: "Web Application",
    nameFr: "Application Web",
    category: "websites_apps",
    description: "Custom dashboards, booking systems, and client portals.",
    descriptionFr: "Tableaux de bord, réservations et portails clients sur mesure.",
    features: ["Custom UI", "Auth + roles", "API integration"],
    price: 350000,
    active: false,
    featured: false,
    order: 2,
  },
  {
    id: "offer-automation",
    slug: "crm-automation",
    name: "CRM & Lead Automation",
    nameFr: "Automatisation CRM",
    category: "automations",
    description: "Automated lead capture, follow-ups, and pipeline workflows.",
    descriptionFr: "Capture leads, relances et workflows pipeline automatisés.",
    features: ["Form integrations", "Email sequences", "Pixel tracking"],
    priceLabel: "Starting from 150,000 DZD",
    active: true,
    featured: false,
    order: 1,
  },
  {
    id: "offer-chatbot",
    slug: "ai-chatbot",
    name: "AI Chatbot",
    nameFr: "Chatbot IA",
    category: "automations",
    description: "WhatsApp and website chatbot for 24/7 customer support.",
    descriptionFr: "Chatbot WhatsApp et site pour support client 24/7.",
    features: ["FAQ training", "Lead qualification", "Handoff to human"],
    price: 180000,
    active: true,
    featured: false,
    order: 2,
  },
];
