import type { TeamMember } from "@/lib/types/admin";

export const TEAM: TeamMember[] = [
  {
    id: "amine",
    name: "Amine",
    role: "ceo",
    displayRole: "CEO + Commercial",
    responsibilities: ["Strategy", "Revenue", "Final approvals"],
    reportsTo: [],
    adminAccess: "full",
    active: true,
  },
  {
    id: "zaki",
    name: "Zaki",
    role: "cto",
    displayRole: "CTO + Head of Content + AI Automation",
    responsibilities: ["Content system", "Calendar", "Automation supervision"],
    reportsTo: ["amine"],
    adminAccess: "full_no_billing",
    active: true,
  },
  {
    id: "anis",
    name: "Anis",
    role: "web_dev",
    displayRole: "Web Developer",
    responsibilities: ["Website build", "Forms + checkout", "Tracking"],
    reportsTo: ["zaki", "amine"],
    adminAccess: "tasks_only",
    active: true,
  },
  {
    id: "yacine",
    name: "Yacine",
    role: "videographer",
    displayRole: "Videographer + Editor",
    responsibilities: ["Shooting", "Editing", "Exports + delivery"],
    reportsTo: ["zaki", "amine"],
    adminAccess: "tasks_only",
    active: true,
  },
  {
    id: "imen",
    name: "Imen",
    role: "designer",
    displayRole: "Designer",
    responsibilities: ["Carousels", "Posters", "Brand assets"],
    reportsTo: ["zaki", "amine"],
    adminAccess: "tasks_only",
    active: true,
  },
];
