/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookRouteImport } from './routes/book'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPipelineRouteImport } from './routes/admin/pipeline'
import { Route as AdminOnboardingRouteImport } from './routes/admin/onboarding'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminServicesIndexRouteImport } from './routes/admin/services/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics/index'
import { Route as AdminTeamUsersRouteImport } from './routes/admin/team/users'
import { Route as AdminTeamRolesRouteImport } from './routes/admin/team/roles'
import { Route as AdminTeamInvitationsRouteImport } from './routes/admin/team/invitations'
import { Route as AdminTeamAuditRouteImport } from './routes/admin/team/audit'
import { Route as AdminSettingsProfileRouteImport } from './routes/admin/settings/profile'
import { Route as AdminSettingsPlatformRouteImport } from './routes/admin/settings/platform'
import { Route as AdminSettingsIntegrationsRouteImport } from './routes/admin/settings/integrations'
import { Route as AdminServicesSponsorsRouteImport } from './routes/admin/services/sponsors'
import { Route as AdminServicesPhotographyRouteImport } from './routes/admin/services/photography'
import { Route as AdminServicesMarketingRouteImport } from './routes/admin/services/marketing'
import { Route as AdminServicesDigitalRouteImport } from './routes/admin/services/digital'
import { Route as AdminServicesAutomationsRouteImport } from './routes/admin/services/automations'
import { Route as AdminProjectsTasksRouteImport } from './routes/admin/projects/tasks'
import { Route as AdminProjectsCalendarRouteImport } from './routes/admin/projects/calendar'
import { Route as AdminProjectsAssetsRouteImport } from './routes/admin/projects/assets'
import { Route as AdminMarketingPixelsRouteImport } from './routes/admin/marketing/pixels'
import { Route as AdminMarketingEventsRouteImport } from './routes/admin/marketing/events'
import { Route as AdminMarketingCampaignsRouteImport } from './routes/admin/marketing/campaigns'
import { Route as AdminMarketingAudiencesRouteImport } from './routes/admin/marketing/audiences'
import { Route as AdminMarketingAttributionRouteImport } from './routes/admin/marketing/attribution'
import { Route as AdminFormsTemplatesRouteImport } from './routes/admin/forms/templates'
import { Route as AdminFormsSubmissionsRouteImport } from './routes/admin/forms/submissions'
import { Route as AdminFormsBuilderRouteImport } from './routes/admin/forms/builder'
import { Route as AdminCommunicationsTemplatesRouteImport } from './routes/admin/communications/templates'
import { Route as AdminCommunicationsNotificationsRouteImport } from './routes/admin/communications/notifications'
import { Route as AdminCommunicationsInboxRouteImport } from './routes/admin/communications/inbox'
import { Route as AdminBillingSubscriptionsRouteImport } from './routes/admin/billing/subscriptions'
import { Route as AdminBillingQuotesRouteImport } from './routes/admin/billing/quotes'
import { Route as AdminBillingInvoicesRouteImport } from './routes/admin/billing/invoices'
import { Route as AdminAnalyticsServicesRouteImport } from './routes/admin/analytics/services'
import { Route as AdminAnalyticsRevenueRouteImport } from './routes/admin/analytics/revenue'
import { Route as AdminAnalyticsReportsRouteImport } from './routes/admin/analytics/reports'
import { Route as AdminAnalyticsPixelsRouteImport } from './routes/admin/analytics/pixels'
import { Route as AdminAnalyticsMarketingRouteImport } from './routes/admin/analytics/marketing'
import { Route as AdminAnalyticsFormsRouteImport } from './routes/admin/analytics/forms'
import { Route as AdminAnalyticsExportsRouteImport } from './routes/admin/analytics/exports'
import { Route as AdminAnalyticsClientsRouteImport } from './routes/admin/analytics/clients'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamUsersRoute = AdminTeamUsersRouteImport.update({
  id: '/team/users',
  path: '/team/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamRolesRoute = AdminTeamRolesRouteImport.update({
  id: '/team/roles',
  path: '/team/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamInvitationsRoute = AdminTeamInvitationsRouteImport.update({
  id: '/team/invitations',
  path: '/team/invitations',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamAuditRoute = AdminTeamAuditRouteImport.update({
  id: '/team/audit',
  path: '/team/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsProfileRoute = AdminSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsPlatformRoute = AdminSettingsPlatformRouteImport.update({
  id: '/settings/platform',
  path: '/settings/platform',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIntegrationsRoute =
  AdminSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminServicesSponsorsRoute = AdminServicesSponsorsRouteImport.update({
  id: '/services/sponsors',
  path: '/services/sponsors',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesPhotographyRoute =
  AdminServicesPhotographyRouteImport.update({
    id: '/services/photography',
    path: '/services/photography',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminServicesMarketingRoute = AdminServicesMarketingRouteImport.update({
  id: '/services/marketing',
  path: '/services/marketing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesDigitalRoute = AdminServicesDigitalRouteImport.update({
  id: '/services/digital',
  path: '/services/digital',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesAutomationsRoute =
  AdminServicesAutomationsRouteImport.update({
    id: '/services/automations',
    path: '/services/automations',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProjectsTasksRoute = AdminProjectsTasksRouteImport.update({
  id: '/projects/tasks',
  path: '/projects/tasks',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsCalendarRoute = AdminProjectsCalendarRouteImport.update({
  id: '/projects/calendar',
  path: '/projects/calendar',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsAssetsRoute = AdminProjectsAssetsRouteImport.update({
  id: '/projects/assets',
  path: '/projects/assets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMarketingPixelsRoute = AdminMarketingPixelsRouteImport.update({
  id: '/marketing/pixels',
  path: '/marketing/pixels',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMarketingEventsRoute = AdminMarketingEventsRouteImport.update({
  id: '/marketing/events',
  path: '/marketing/events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMarketingCampaignsRoute = AdminMarketingCampaignsRouteImport.update({
  id: '/marketing/campaigns',
  path: '/marketing/campaigns',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMarketingAudiencesRoute = AdminMarketingAudiencesRouteImport.update({
  id: '/marketing/audiences',
  path: '/marketing/audiences',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMarketingAttributionRoute =
  AdminMarketingAttributionRouteImport.update({
    id: '/marketing/attribution',
    path: '/marketing/attribution',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminFormsTemplatesRoute = AdminFormsTemplatesRouteImport.update({
  id: '/forms/templates',
  path: '/forms/templates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsSubmissionsRoute = AdminFormsSubmissionsRouteImport.update({
  id: '/forms/submissions',
  path: '/forms/submissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFormsBuilderRoute = AdminFormsBuilderRouteImport.update({
  id: '/forms/builder',
  path: '/forms/builder',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommunicationsTemplatesRoute =
  AdminCommunicationsTemplatesRouteImport.update({
    id: '/communications/templates',
    path: '/communications/templates',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCommunicationsNotificationsRoute =
  AdminCommunicationsNotificationsRouteImport.update({
    id: '/communications/notifications',
    path: '/communications/notifications',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCommunicationsInboxRoute =
  AdminCommunicationsInboxRouteImport.update({
    id: '/communications/inbox',
    path: '/communications/inbox',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminBillingSubscriptionsRoute =
  AdminBillingSubscriptionsRouteImport.update({
    id: '/billing/subscriptions',
    path: '/billing/subscriptions',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminBillingQuotesRoute = AdminBillingQuotesRouteImport.update({
  id: '/billing/quotes',
  path: '/billing/quotes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingInvoicesRoute = AdminBillingInvoicesRouteImport.update({
  id: '/billing/invoices',
  path: '/billing/invoices',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsServicesRoute = AdminAnalyticsServicesRouteImport.update({
  id: '/analytics/services',
  path: '/analytics/services',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRevenueRoute = AdminAnalyticsRevenueRouteImport.update({
  id: '/analytics/revenue',
  path: '/analytics/revenue',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsReportsRoute = AdminAnalyticsReportsRouteImport.update({
  id: '/analytics/reports',
  path: '/analytics/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsPixelsRoute = AdminAnalyticsPixelsRouteImport.update({
  id: '/analytics/pixels',
  path: '/analytics/pixels',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsMarketingRoute = AdminAnalyticsMarketingRouteImport.update({
  id: '/analytics/marketing',
  path: '/analytics/marketing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsFormsRoute = AdminAnalyticsFormsRouteImport.update({
  id: '/analytics/forms',
  path: '/analytics/forms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsExportsRoute = AdminAnalyticsExportsRouteImport.update({
  id: '/analytics/exports',
  path: '/analytics/exports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsClientsRoute = AdminAnalyticsClientsRouteImport.update({
  id: '/analytics/clients',
  path: '/analytics/clients',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/analytics/clients': typeof AdminAnalyticsClientsRoute
  '/admin/analytics/exports': typeof AdminAnalyticsExportsRoute
  '/admin/analytics/forms': typeof AdminAnalyticsFormsRoute
  '/admin/analytics/marketing': typeof AdminAnalyticsMarketingRoute
  '/admin/analytics/pixels': typeof AdminAnalyticsPixelsRoute
  '/admin/analytics/reports': typeof AdminAnalyticsReportsRoute
  '/admin/analytics/revenue': typeof AdminAnalyticsRevenueRoute
  '/admin/analytics/services': typeof AdminAnalyticsServicesRoute
  '/admin/billing/invoices': typeof AdminBillingInvoicesRoute
  '/admin/billing/quotes': typeof AdminBillingQuotesRoute
  '/admin/billing/subscriptions': typeof AdminBillingSubscriptionsRoute
  '/admin/communications/inbox': typeof AdminCommunicationsInboxRoute
  '/admin/communications/notifications': typeof AdminCommunicationsNotificationsRoute
  '/admin/communications/templates': typeof AdminCommunicationsTemplatesRoute
  '/admin/forms/builder': typeof AdminFormsBuilderRoute
  '/admin/forms/submissions': typeof AdminFormsSubmissionsRoute
  '/admin/forms/templates': typeof AdminFormsTemplatesRoute
  '/admin/marketing/attribution': typeof AdminMarketingAttributionRoute
  '/admin/marketing/audiences': typeof AdminMarketingAudiencesRoute
  '/admin/marketing/campaigns': typeof AdminMarketingCampaignsRoute
  '/admin/marketing/events': typeof AdminMarketingEventsRoute
  '/admin/marketing/pixels': typeof AdminMarketingPixelsRoute
  '/admin/projects/assets': typeof AdminProjectsAssetsRoute
  '/admin/projects/calendar': typeof AdminProjectsCalendarRoute
  '/admin/projects/tasks': typeof AdminProjectsTasksRoute
  '/admin/services/automations': typeof AdminServicesAutomationsRoute
  '/admin/services/digital': typeof AdminServicesDigitalRoute
  '/admin/services/marketing': typeof AdminServicesMarketingRoute
  '/admin/services/photography': typeof AdminServicesPhotographyRoute
  '/admin/services/sponsors': typeof AdminServicesSponsorsRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/platform': typeof AdminSettingsPlatformRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/admin/team/audit': typeof AdminTeamAuditRoute
  '/admin/team/invitations': typeof AdminTeamInvitationsRoute
  '/admin/team/roles': typeof AdminTeamRolesRoute
  '/admin/team/users': typeof AdminTeamUsersRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin': typeof AdminIndexRoute
  '/admin/analytics/clients': typeof AdminAnalyticsClientsRoute
  '/admin/analytics/exports': typeof AdminAnalyticsExportsRoute
  '/admin/analytics/forms': typeof AdminAnalyticsFormsRoute
  '/admin/analytics/marketing': typeof AdminAnalyticsMarketingRoute
  '/admin/analytics/pixels': typeof AdminAnalyticsPixelsRoute
  '/admin/analytics/reports': typeof AdminAnalyticsReportsRoute
  '/admin/analytics/revenue': typeof AdminAnalyticsRevenueRoute
  '/admin/analytics/services': typeof AdminAnalyticsServicesRoute
  '/admin/billing/invoices': typeof AdminBillingInvoicesRoute
  '/admin/billing/quotes': typeof AdminBillingQuotesRoute
  '/admin/billing/subscriptions': typeof AdminBillingSubscriptionsRoute
  '/admin/communications/inbox': typeof AdminCommunicationsInboxRoute
  '/admin/communications/notifications': typeof AdminCommunicationsNotificationsRoute
  '/admin/communications/templates': typeof AdminCommunicationsTemplatesRoute
  '/admin/forms/builder': typeof AdminFormsBuilderRoute
  '/admin/forms/submissions': typeof AdminFormsSubmissionsRoute
  '/admin/forms/templates': typeof AdminFormsTemplatesRoute
  '/admin/marketing/attribution': typeof AdminMarketingAttributionRoute
  '/admin/marketing/audiences': typeof AdminMarketingAudiencesRoute
  '/admin/marketing/campaigns': typeof AdminMarketingCampaignsRoute
  '/admin/marketing/events': typeof AdminMarketingEventsRoute
  '/admin/marketing/pixels': typeof AdminMarketingPixelsRoute
  '/admin/projects/assets': typeof AdminProjectsAssetsRoute
  '/admin/projects/calendar': typeof AdminProjectsCalendarRoute
  '/admin/projects/tasks': typeof AdminProjectsTasksRoute
  '/admin/services/automations': typeof AdminServicesAutomationsRoute
  '/admin/services/digital': typeof AdminServicesDigitalRoute
  '/admin/services/marketing': typeof AdminServicesMarketingRoute
  '/admin/services/photography': typeof AdminServicesPhotographyRoute
  '/admin/services/sponsors': typeof AdminServicesSponsorsRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/platform': typeof AdminSettingsPlatformRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/admin/team/audit': typeof AdminTeamAuditRoute
  '/admin/team/invitations': typeof AdminTeamInvitationsRoute
  '/admin/team/roles': typeof AdminTeamRolesRoute
  '/admin/team/users': typeof AdminTeamUsersRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/analytics/clients': typeof AdminAnalyticsClientsRoute
  '/admin/analytics/exports': typeof AdminAnalyticsExportsRoute
  '/admin/analytics/forms': typeof AdminAnalyticsFormsRoute
  '/admin/analytics/marketing': typeof AdminAnalyticsMarketingRoute
  '/admin/analytics/pixels': typeof AdminAnalyticsPixelsRoute
  '/admin/analytics/reports': typeof AdminAnalyticsReportsRoute
  '/admin/analytics/revenue': typeof AdminAnalyticsRevenueRoute
  '/admin/analytics/services': typeof AdminAnalyticsServicesRoute
  '/admin/billing/invoices': typeof AdminBillingInvoicesRoute
  '/admin/billing/quotes': typeof AdminBillingQuotesRoute
  '/admin/billing/subscriptions': typeof AdminBillingSubscriptionsRoute
  '/admin/communications/inbox': typeof AdminCommunicationsInboxRoute
  '/admin/communications/notifications': typeof AdminCommunicationsNotificationsRoute
  '/admin/communications/templates': typeof AdminCommunicationsTemplatesRoute
  '/admin/forms/builder': typeof AdminFormsBuilderRoute
  '/admin/forms/submissions': typeof AdminFormsSubmissionsRoute
  '/admin/forms/templates': typeof AdminFormsTemplatesRoute
  '/admin/marketing/attribution': typeof AdminMarketingAttributionRoute
  '/admin/marketing/audiences': typeof AdminMarketingAudiencesRoute
  '/admin/marketing/campaigns': typeof AdminMarketingCampaignsRoute
  '/admin/marketing/events': typeof AdminMarketingEventsRoute
  '/admin/marketing/pixels': typeof AdminMarketingPixelsRoute
  '/admin/projects/assets': typeof AdminProjectsAssetsRoute
  '/admin/projects/calendar': typeof AdminProjectsCalendarRoute
  '/admin/projects/tasks': typeof AdminProjectsTasksRoute
  '/admin/services/automations': typeof AdminServicesAutomationsRoute
  '/admin/services/digital': typeof AdminServicesDigitalRoute
  '/admin/services/marketing': typeof AdminServicesMarketingRoute
  '/admin/services/photography': typeof AdminServicesPhotographyRoute
  '/admin/services/sponsors': typeof AdminServicesSponsorsRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/platform': typeof AdminSettingsPlatformRoute
  '/admin/settings/profile': typeof AdminSettingsProfileRoute
  '/admin/team/audit': typeof AdminTeamAuditRoute
  '/admin/team/invitations': typeof AdminTeamInvitationsRoute
  '/admin/team/roles': typeof AdminTeamRolesRoute
  '/admin/team/users': typeof AdminTeamUsersRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/book'
    | '/login'
    | '/admin/clients'
    | '/admin/contacts'
    | '/admin/leads'
    | '/admin/onboarding'
    | '/admin/pipeline'
    | '/admin/'
    | '/admin/analytics/clients'
    | '/admin/analytics/exports'
    | '/admin/analytics/forms'
    | '/admin/analytics/marketing'
    | '/admin/analytics/pixels'
    | '/admin/analytics/reports'
    | '/admin/analytics/revenue'
    | '/admin/analytics/services'
    | '/admin/billing/invoices'
    | '/admin/billing/quotes'
    | '/admin/billing/subscriptions'
    | '/admin/communications/inbox'
    | '/admin/communications/notifications'
    | '/admin/communications/templates'
    | '/admin/forms/builder'
    | '/admin/forms/submissions'
    | '/admin/forms/templates'
    | '/admin/marketing/attribution'
    | '/admin/marketing/audiences'
    | '/admin/marketing/campaigns'
    | '/admin/marketing/events'
    | '/admin/marketing/pixels'
    | '/admin/projects/assets'
    | '/admin/projects/calendar'
    | '/admin/projects/tasks'
    | '/admin/services/automations'
    | '/admin/services/digital'
    | '/admin/services/marketing'
    | '/admin/services/photography'
    | '/admin/services/sponsors'
    | '/admin/settings/integrations'
    | '/admin/settings/platform'
    | '/admin/settings/profile'
    | '/admin/team/audit'
    | '/admin/team/invitations'
    | '/admin/team/roles'
    | '/admin/team/users'
    | '/admin/analytics/'
    | '/admin/projects/'
    | '/admin/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/login'
    | '/admin/clients'
    | '/admin/contacts'
    | '/admin/leads'
    | '/admin/onboarding'
    | '/admin/pipeline'
    | '/admin'
    | '/admin/analytics/clients'
    | '/admin/analytics/exports'
    | '/admin/analytics/forms'
    | '/admin/analytics/marketing'
    | '/admin/analytics/pixels'
    | '/admin/analytics/reports'
    | '/admin/analytics/revenue'
    | '/admin/analytics/services'
    | '/admin/billing/invoices'
    | '/admin/billing/quotes'
    | '/admin/billing/subscriptions'
    | '/admin/communications/inbox'
    | '/admin/communications/notifications'
    | '/admin/communications/templates'
    | '/admin/forms/builder'
    | '/admin/forms/submissions'
    | '/admin/forms/templates'
    | '/admin/marketing/attribution'
    | '/admin/marketing/audiences'
    | '/admin/marketing/campaigns'
    | '/admin/marketing/events'
    | '/admin/marketing/pixels'
    | '/admin/projects/assets'
    | '/admin/projects/calendar'
    | '/admin/projects/tasks'
    | '/admin/services/automations'
    | '/admin/services/digital'
    | '/admin/services/marketing'
    | '/admin/services/photography'
    | '/admin/services/sponsors'
    | '/admin/settings/integrations'
    | '/admin/settings/platform'
    | '/admin/settings/profile'
    | '/admin/team/audit'
    | '/admin/team/invitations'
    | '/admin/team/roles'
    | '/admin/team/users'
    | '/admin/analytics'
    | '/admin/projects'
    | '/admin/services'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/book'
    | '/login'
    | '/admin/clients'
    | '/admin/contacts'
    | '/admin/leads'
    | '/admin/onboarding'
    | '/admin/pipeline'
    | '/admin/'
    | '/admin/analytics/clients'
    | '/admin/analytics/exports'
    | '/admin/analytics/forms'
    | '/admin/analytics/marketing'
    | '/admin/analytics/pixels'
    | '/admin/analytics/reports'
    | '/admin/analytics/revenue'
    | '/admin/analytics/services'
    | '/admin/billing/invoices'
    | '/admin/billing/quotes'
    | '/admin/billing/subscriptions'
    | '/admin/communications/inbox'
    | '/admin/communications/notifications'
    | '/admin/communications/templates'
    | '/admin/forms/builder'
    | '/admin/forms/submissions'
    | '/admin/forms/templates'
    | '/admin/marketing/attribution'
    | '/admin/marketing/audiences'
    | '/admin/marketing/campaigns'
    | '/admin/marketing/events'
    | '/admin/marketing/pixels'
    | '/admin/projects/assets'
    | '/admin/projects/calendar'
    | '/admin/projects/tasks'
    | '/admin/services/automations'
    | '/admin/services/digital'
    | '/admin/services/marketing'
    | '/admin/services/photography'
    | '/admin/services/sponsors'
    | '/admin/settings/integrations'
    | '/admin/settings/platform'
    | '/admin/settings/profile'
    | '/admin/team/audit'
    | '/admin/team/invitations'
    | '/admin/team/roles'
    | '/admin/team/users'
    | '/admin/analytics/'
    | '/admin/projects/'
    | '/admin/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BookRoute: typeof BookRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team/users': {
      id: '/admin/team/users'
      path: '/team/users'
      fullPath: '/admin/team/users'
      preLoaderRoute: typeof AdminTeamUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team/roles': {
      id: '/admin/team/roles'
      path: '/team/roles'
      fullPath: '/admin/team/roles'
      preLoaderRoute: typeof AdminTeamRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team/invitations': {
      id: '/admin/team/invitations'
      path: '/team/invitations'
      fullPath: '/admin/team/invitations'
      preLoaderRoute: typeof AdminTeamInvitationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team/audit': {
      id: '/admin/team/audit'
      path: '/team/audit'
      fullPath: '/admin/team/audit'
      preLoaderRoute: typeof AdminTeamAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/profile': {
      id: '/admin/settings/profile'
      path: '/settings/profile'
      fullPath: '/admin/settings/profile'
      preLoaderRoute: typeof AdminSettingsProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/platform': {
      id: '/admin/settings/platform'
      path: '/settings/platform'
      fullPath: '/admin/settings/platform'
      preLoaderRoute: typeof AdminSettingsPlatformRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings/integrations': {
      id: '/admin/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/admin/settings/integrations'
      preLoaderRoute: typeof AdminSettingsIntegrationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/sponsors': {
      id: '/admin/services/sponsors'
      path: '/services/sponsors'
      fullPath: '/admin/services/sponsors'
      preLoaderRoute: typeof AdminServicesSponsorsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/photography': {
      id: '/admin/services/photography'
      path: '/services/photography'
      fullPath: '/admin/services/photography'
      preLoaderRoute: typeof AdminServicesPhotographyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/marketing': {
      id: '/admin/services/marketing'
      path: '/services/marketing'
      fullPath: '/admin/services/marketing'
      preLoaderRoute: typeof AdminServicesMarketingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/digital': {
      id: '/admin/services/digital'
      path: '/services/digital'
      fullPath: '/admin/services/digital'
      preLoaderRoute: typeof AdminServicesDigitalRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/services/automations': {
      id: '/admin/services/automations'
      path: '/services/automations'
      fullPath: '/admin/services/automations'
      preLoaderRoute: typeof AdminServicesAutomationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/tasks': {
      id: '/admin/projects/tasks'
      path: '/projects/tasks'
      fullPath: '/admin/projects/tasks'
      preLoaderRoute: typeof AdminProjectsTasksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/calendar': {
      id: '/admin/projects/calendar'
      path: '/projects/calendar'
      fullPath: '/admin/projects/calendar'
      preLoaderRoute: typeof AdminProjectsCalendarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects/assets': {
      id: '/admin/projects/assets'
      path: '/projects/assets'
      fullPath: '/admin/projects/assets'
      preLoaderRoute: typeof AdminProjectsAssetsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/marketing/pixels': {
      id: '/admin/marketing/pixels'
      path: '/marketing/pixels'
      fullPath: '/admin/marketing/pixels'
      preLoaderRoute: typeof AdminMarketingPixelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/marketing/events': {
      id: '/admin/marketing/events'
      path: '/marketing/events'
      fullPath: '/admin/marketing/events'
      preLoaderRoute: typeof AdminMarketingEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/marketing/campaigns': {
      id: '/admin/marketing/campaigns'
      path: '/marketing/campaigns'
      fullPath: '/admin/marketing/campaigns'
      preLoaderRoute: typeof AdminMarketingCampaignsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/marketing/audiences': {
      id: '/admin/marketing/audiences'
      path: '/marketing/audiences'
      fullPath: '/admin/marketing/audiences'
      preLoaderRoute: typeof AdminMarketingAudiencesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/marketing/attribution': {
      id: '/admin/marketing/attribution'
      path: '/marketing/attribution'
      fullPath: '/admin/marketing/attribution'
      preLoaderRoute: typeof AdminMarketingAttributionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forms/templates': {
      id: '/admin/forms/templates'
      path: '/forms/templates'
      fullPath: '/admin/forms/templates'
      preLoaderRoute: typeof AdminFormsTemplatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forms/submissions': {
      id: '/admin/forms/submissions'
      path: '/forms/submissions'
      fullPath: '/admin/forms/submissions'
      preLoaderRoute: typeof AdminFormsSubmissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forms/builder': {
      id: '/admin/forms/builder'
      path: '/forms/builder'
      fullPath: '/admin/forms/builder'
      preLoaderRoute: typeof AdminFormsBuilderRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/communications/templates': {
      id: '/admin/communications/templates'
      path: '/communications/templates'
      fullPath: '/admin/communications/templates'
      preLoaderRoute: typeof AdminCommunicationsTemplatesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/communications/notifications': {
      id: '/admin/communications/notifications'
      path: '/communications/notifications'
      fullPath: '/admin/communications/notifications'
      preLoaderRoute: typeof AdminCommunicationsNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/communications/inbox': {
      id: '/admin/communications/inbox'
      path: '/communications/inbox'
      fullPath: '/admin/communications/inbox'
      preLoaderRoute: typeof AdminCommunicationsInboxRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing/subscriptions': {
      id: '/admin/billing/subscriptions'
      path: '/billing/subscriptions'
      fullPath: '/admin/billing/subscriptions'
      preLoaderRoute: typeof AdminBillingSubscriptionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing/quotes': {
      id: '/admin/billing/quotes'
      path: '/billing/quotes'
      fullPath: '/admin/billing/quotes'
      preLoaderRoute: typeof AdminBillingQuotesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing/invoices': {
      id: '/admin/billing/invoices'
      path: '/billing/invoices'
      fullPath: '/admin/billing/invoices'
      preLoaderRoute: typeof AdminBillingInvoicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/services': {
      id: '/admin/analytics/services'
      path: '/analytics/services'
      fullPath: '/admin/analytics/services'
      preLoaderRoute: typeof AdminAnalyticsServicesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/revenue': {
      id: '/admin/analytics/revenue'
      path: '/analytics/revenue'
      fullPath: '/admin/analytics/revenue'
      preLoaderRoute: typeof AdminAnalyticsRevenueRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/reports': {
      id: '/admin/analytics/reports'
      path: '/analytics/reports'
      fullPath: '/admin/analytics/reports'
      preLoaderRoute: typeof AdminAnalyticsReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/pixels': {
      id: '/admin/analytics/pixels'
      path: '/analytics/pixels'
      fullPath: '/admin/analytics/pixels'
      preLoaderRoute: typeof AdminAnalyticsPixelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/marketing': {
      id: '/admin/analytics/marketing'
      path: '/analytics/marketing'
      fullPath: '/admin/analytics/marketing'
      preLoaderRoute: typeof AdminAnalyticsMarketingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/forms': {
      id: '/admin/analytics/forms'
      path: '/analytics/forms'
      fullPath: '/admin/analytics/forms'
      preLoaderRoute: typeof AdminAnalyticsFormsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/exports': {
      id: '/admin/analytics/exports'
      path: '/analytics/exports'
      fullPath: '/admin/analytics/exports'
      preLoaderRoute: typeof AdminAnalyticsExportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/clients': {
      id: '/admin/analytics/clients'
      path: '/analytics/clients'
      fullPath: '/admin/analytics/clients'
      preLoaderRoute: typeof AdminAnalyticsClientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalyticsClientsRoute: typeof AdminAnalyticsClientsRoute
  AdminAnalyticsExportsRoute: typeof AdminAnalyticsExportsRoute
  AdminAnalyticsFormsRoute: typeof AdminAnalyticsFormsRoute
  AdminAnalyticsMarketingRoute: typeof AdminAnalyticsMarketingRoute
  AdminAnalyticsPixelsRoute: typeof AdminAnalyticsPixelsRoute
  AdminAnalyticsReportsRoute: typeof AdminAnalyticsReportsRoute
  AdminAnalyticsRevenueRoute: typeof AdminAnalyticsRevenueRoute
  AdminAnalyticsServicesRoute: typeof AdminAnalyticsServicesRoute
  AdminBillingInvoicesRoute: typeof AdminBillingInvoicesRoute
  AdminBillingQuotesRoute: typeof AdminBillingQuotesRoute
  AdminBillingSubscriptionsRoute: typeof AdminBillingSubscriptionsRoute
  AdminCommunicationsInboxRoute: typeof AdminCommunicationsInboxRoute
  AdminCommunicationsNotificationsRoute: typeof AdminCommunicationsNotificationsRoute
  AdminCommunicationsTemplatesRoute: typeof AdminCommunicationsTemplatesRoute
  AdminFormsBuilderRoute: typeof AdminFormsBuilderRoute
  AdminFormsSubmissionsRoute: typeof AdminFormsSubmissionsRoute
  AdminFormsTemplatesRoute: typeof AdminFormsTemplatesRoute
  AdminMarketingAttributionRoute: typeof AdminMarketingAttributionRoute
  AdminMarketingAudiencesRoute: typeof AdminMarketingAudiencesRoute
  AdminMarketingCampaignsRoute: typeof AdminMarketingCampaignsRoute
  AdminMarketingEventsRoute: typeof AdminMarketingEventsRoute
  AdminMarketingPixelsRoute: typeof AdminMarketingPixelsRoute
  AdminProjectsAssetsRoute: typeof AdminProjectsAssetsRoute
  AdminProjectsCalendarRoute: typeof AdminProjectsCalendarRoute
  AdminProjectsTasksRoute: typeof AdminProjectsTasksRoute
  AdminServicesAutomationsRoute: typeof AdminServicesAutomationsRoute
  AdminServicesDigitalRoute: typeof AdminServicesDigitalRoute
  AdminServicesMarketingRoute: typeof AdminServicesMarketingRoute
  AdminServicesPhotographyRoute: typeof AdminServicesPhotographyRoute
  AdminServicesSponsorsRoute: typeof AdminServicesSponsorsRoute
  AdminSettingsIntegrationsRoute: typeof AdminSettingsIntegrationsRoute
  AdminSettingsPlatformRoute: typeof AdminSettingsPlatformRoute
  AdminSettingsProfileRoute: typeof AdminSettingsProfileRoute
  AdminTeamAuditRoute: typeof AdminTeamAuditRoute
  AdminTeamInvitationsRoute: typeof AdminTeamInvitationsRoute
  AdminTeamRolesRoute: typeof AdminTeamRolesRoute
  AdminTeamUsersRoute: typeof AdminTeamUsersRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalyticsClientsRoute: AdminAnalyticsClientsRoute,
  AdminAnalyticsExportsRoute: AdminAnalyticsExportsRoute,
  AdminAnalyticsFormsRoute: AdminAnalyticsFormsRoute,
  AdminAnalyticsMarketingRoute: AdminAnalyticsMarketingRoute,
  AdminAnalyticsPixelsRoute: AdminAnalyticsPixelsRoute,
  AdminAnalyticsReportsRoute: AdminAnalyticsReportsRoute,
  AdminAnalyticsRevenueRoute: AdminAnalyticsRevenueRoute,
  AdminAnalyticsServicesRoute: AdminAnalyticsServicesRoute,
  AdminBillingInvoicesRoute: AdminBillingInvoicesRoute,
  AdminBillingQuotesRoute: AdminBillingQuotesRoute,
  AdminBillingSubscriptionsRoute: AdminBillingSubscriptionsRoute,
  AdminCommunicationsInboxRoute: AdminCommunicationsInboxRoute,
  AdminCommunicationsNotificationsRoute: AdminCommunicationsNotificationsRoute,
  AdminCommunicationsTemplatesRoute: AdminCommunicationsTemplatesRoute,
  AdminFormsBuilderRoute: AdminFormsBuilderRoute,
  AdminFormsSubmissionsRoute: AdminFormsSubmissionsRoute,
  AdminFormsTemplatesRoute: AdminFormsTemplatesRoute,
  AdminMarketingAttributionRoute: AdminMarketingAttributionRoute,
  AdminMarketingAudiencesRoute: AdminMarketingAudiencesRoute,
  AdminMarketingCampaignsRoute: AdminMarketingCampaignsRoute,
  AdminMarketingEventsRoute: AdminMarketingEventsRoute,
  AdminMarketingPixelsRoute: AdminMarketingPixelsRoute,
  AdminProjectsAssetsRoute: AdminProjectsAssetsRoute,
  AdminProjectsCalendarRoute: AdminProjectsCalendarRoute,
  AdminProjectsTasksRoute: AdminProjectsTasksRoute,
  AdminServicesAutomationsRoute: AdminServicesAutomationsRoute,
  AdminServicesDigitalRoute: AdminServicesDigitalRoute,
  AdminServicesMarketingRoute: AdminServicesMarketingRoute,
  AdminServicesPhotographyRoute: AdminServicesPhotographyRoute,
  AdminServicesSponsorsRoute: AdminServicesSponsorsRoute,
  AdminSettingsIntegrationsRoute: AdminSettingsIntegrationsRoute,
  AdminSettingsPlatformRoute: AdminSettingsPlatformRoute,
  AdminSettingsProfileRoute: AdminSettingsProfileRoute,
  AdminTeamAuditRoute: AdminTeamAuditRoute,
  AdminTeamInvitationsRoute: AdminTeamInvitationsRoute,
  AdminTeamRolesRoute: AdminTeamRolesRoute,
  AdminTeamUsersRoute: AdminTeamUsersRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BookRoute: BookRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
